name: "Compile Elm"
description: "Takes a single string with different paths to elm files, parses them and runs a make command on them for every file"


inputs:
  elm_paths:
    description: "A string of all elm files"
    required: True

runs:
  using: "composite"
  steps:
    #- name: Setup Node
      #uses: actions/setup-node@v3
      #with:
        #node-version: '16'
    - name: compile script
      run: ./compile.sh
      shell: bash
      env:
        Elm_Path: ${{ inputs.elm_paths }}
        Project_Name: ${{ env.PROJECT_NAME }}
        Workspace: ${{ github.workspace }}