name: "Compile Elm"
description: "Takes a single string with different paths to elm files, parses them and runs a make command on them for every file"


inputs:
  elm-paths:
    description: "A string of all elm files"
    required: True
  elm-version:
    description: "Version of elm to be used to compile the projects elm files"
    required: True
    default: 0.19.1

runs:
  using: "composite"
  steps:
    - name: pre-compile
      run: echo "Preparing to execute compile script"
      shell: bash
    - name: Print path
      run: echo pwd
      shell: bash
    - name: compile script
      run: ./compile.sh
      shell: bash
      env:
        ELM_VERSION: ${{ inputs.elm-version }}
        ELM_PATHS: ${{ inputs.elm-paths }}
        WORKSPACE: ${{ env.GITHUB_WORKSPACE }}