name: Test Compile Elm
on: [workflow_dispatch]

env:
  PROJECT_NAME: testgha
  GITHUB_WORKSPACE : ${{ github.workspace }}
  ELM_PATHS: first second

jobs:
  compile_elm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: compile
        uses: ./
        with:
          elm-paths: ${{ env.ELM_PATHS }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: elm-to- js
          path: |
            wagtail
            !wagtail/**/*.md
